[project]
name = "codalpy"
version = "0.3.3"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastexcel>=0.13.0",
    "jdatetime>=5.2.0",
    "polars>=1.24.0",
    "pyarrow>=19.0.1",
    "pydantic>=2.10.6",
    "requests>=2.32.3",
]

[tool.pyright]
root = "valpy"
venvPath = "."
venv = ".venv"

[dependency-groups]
dev = [
    "black>=25.1.0",
    "isort>=6.0.1",
    "pre-commit>=4.2.0",
]
